[template]
src = "duo.tmpl"
dest = "/etc/duo/pam_duo.conf"
prefix = "/arenas/%%ARENA%%/global/instance_mfa"
keys = [
    "/config"
]

uid = 0
gid = 0
mode = "0600"

reload_cmd = "puppet apply /etc/duo/duo_sshd_config_runtime.pp"
