language: ruby
sudo: false
gemfile: nubis/travis/Gemfile
cache:
  bundler: true
  directories:
  - "${HOME}/bin"
  - nubis/librarian-puppet
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck
script:
- nubis/travis/run-checks
notifications:
  slack:
    secure: XdAmRj2LZIohdnd08zpESje9ljPBvguXb/OBSD8tEuDy8s77LuRXh6Rl31c2oj55ITrwTuQJbsU66TkR31yYplHhIjzik/f1rtfkoNyGAqgZKOOelz4oGtAiuY9qwnvuVuCNgPGPvEW9K9llPF7yGU4h9Ye4XOAvrTbMwgeTuUBtccpEHkD9JX9AxzBuQEtKuOYwD0zw5MKSeAtMgpt8xzsQCroT3fhLJEitoy8R1Nxg/rniFwnaQ26boIuOgjNIUokDgcgMLvOOr88MXvgIn0Z9kPs1zO3Lcqly5LSjtr9T8Y10y68EN8E6mC9Ww+6sLb28T5emB+UiwsJdH9nedfg8dFarlUbQ79UBSdOXKO+7DE5rX6KYIUBXLBtzXGjcZ4APF88g7ejqQ66wwZp9hpjOHZIc8YW6Ao9GH2z69rQi8S4co2OB2z5IgUb47/gsZs9D9Zdz0ctw92xQazkd/ZKDn6F0Gw6QcrlJ/S/qcMB9CPIrsfu+qp5p3eBzCcBzpYgKFP3MVjXOVQ5afWv5Zu92TAks/7KXdgMiiLLOUB2amrUhrLWUZZl5oWgTrhDt+LZAYRqrYRj8AJE6jeyXJSazpC+ElqhD9oUcz6jtHPY0zPnf3HRF02hsm6fBFR87kjLKIwJsMFOCwM/jkjcDRpCa54Uxxh+ZWWn3w/KbdZQ=
