language: ruby
sudo: false
gemfile: nubis/travis/Gemfile
branches:
  except:
  - master
cache:
  bundler: true
  pip: true
  directories:
  - "${HOME}/bin"
  - nubis/librarian-puppet
script:
- nubis/travis/run-checks
- nubis/travis/run-builds
notifications:
  slack:
    secure: Bgu42ldHdcCPJ1pJ0YplS5N3xwU3iS7gbsrJzRMQzBrj3nXYICqLUNFNwClAwUft3CMFHiofV/Y59X2E7likGXB8XX6J8FteL7mEqGifg8ucxrVtNGjztITnxke6XiFq2FC2bjld/RYX0d+eo2ZlkJbwWgLeHFjC+GHmaNLZfy8=
