#!/bin/bash

set -e

# /usr/local/bin isn't set yet in our PATH
export PATH=/usr/local/bin:$PATH

# Wait for nubis-metadata, we will be invoked again soon
if [ "$(nubis-metadata status)" != 'ready' ]; then
    exit 0
fi

if nubis-metadata NUBIS_SUDO_GROUPS > /dev/null 2>&1; then
    NUBIS_SUDO_GROUPS_TMP=$(nubis-metadata NUBIS_SUDO_GROUPS | sed -e's/^/["/g' | sed -e's/$/"]/' | sed -e's/,/","/g')
else
    NUBIS_SUDO_GROUPS_TMP="[]"
fi

if nubis-metadata NUBIS_USER_GROUPS > /dev/null 2>&1; then
    NUBIS_USER_GROUPS_TMP=$(nubis-metadata NUBIS_USER_GROUPS | sed -e's/^/["/g' | sed -e's/$/"]/' | sed -e's/,/","/g')
else
    NUBIS_USER_GROUPS_TMP="[]"
fi

cat <<EOF > /etc/nubis/puppet/nubis_users.pp
# Generated by gen-puppet.sh
class { 'nubis_users::setup':
    sudo_users    => ${NUBIS_SUDO_GROUPS_TMP},
    nubis_users   => ${NUBIS_USER_GROUPS_TMP},
}
EOF

puppet apply /etc/nubis/puppet/nubis_users.pp
