#!/bin/bash

PATH=/usr/local/sbin:/usr/local/bin:$PATH

# Are we tainted ?
if [ ! -r /.tainted ]; then
  # OK
  exit 0
fi

if [ "$(nubis-metadata status)" != 'ready' ]; then
  # Assume this is a Packer Builder, so bail out silently
  exit 0
fi

NUBIS_ARENA=$(nubis-metadata NUBIS_ARENA)
GRACE_FLAG="arenas/$NUBIS_ARENA/global/tainted/grace"
GRACE=$(consulate kv get "$GRACE_FLAG" 2>/dev/null)

# Grace period not enabled
if [ "$GRACE" == "None" ] || [ "$GRACE" == "" ]; then
  GRACE="1 hour"
fi

TAINTED_ON=$(stat -c %z /.tainted)
EXPIRE_ON=$(date --date "$TAINTED_ON +$GRACE" '+%s')
UNIX_NOW=$(date '+%s')

if [ "$EXPIRE_ON" -gt "$UNIX_NOW" ]; then
  echo "Instance is tainted and expires on $(date --date "@$EXPIRE_ON")"
  # Warning
  STATUS=1
else
  echo "Instance is tainted and has expired since $(date --date "@$EXPIRE_ON")"
  # error
  STATUS=2
fi

cat /.tainted

exit $STATUS
