#!/bin/bash

# Load up proxy settings
if [ -r /etc/profile.d/proxy.sh ]; then
  # shellcheck disable=SC1091
  . /etc/profile.d/proxy.sh
fi

# Expose our project to fluentd
NUBIS_PROJECT=$(nubis-metadata NUBIS_PROJECT)
export NUBIS_PROJECT

# Expose our purpose to fluentd
NUBIS_PURPOSE=$(nubis-metadata NUBIS_PURPOSE)
export NUBIS_PURPOSE

#Expose our stack to fluentd
NUBIS_STACK=$(nubis-metadata NUBIS_STACK)
export NUBIS_STACK

#Expose our environment to fluentd
NUBIS_ENVIRONMENT=$(nubis-metadata NUBIS_ENVIRONMENT)
export NUBIS_ENVIRONMENT

#Expose our arena to fluentd
NUBIS_ARENA=$(nubis-metadata NUBIS_ARENA)
export NUBIS_ARENA

exec /opt/td-agent/embedded/bin/fluentd --log /var/log/td-agent/td-agent.log --daemon /var/run/td-agent/td-agent.pid
