#!/bin/bash

# Be explicit to be safe
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Are we tainted to start with?
nubis-tainted > /dev/null
TAINTED=$?

if [ "$TAINTED" == "0" ]; then
  exit
fi

# Is there anybody logged on ?
LOGGED_ON_USERS=$(w -h | wc -l)
if [ "$LOGGED_ON_USERS" != 0 ]; then
  exit
fi

# Tainted = 1 is just a warning we are tainted
# Tainted > 1 means we have expired
if [ "$TAINTED" -gt "1" ] && [ "$(nubis-metadata status)" == 'ready' ]; then
  NUBIS_ARENA=$(nubis-metadata NUBIS_ARENA)
  DELETE_FLAG="arenas/$NUBIS_ARENA/global/tainted/delete"
  DELETE_ENABLED=$(consulate kv get "$DELETE_FLAG")

  if [ "$DELETE_ENABLED" == "0" ]; then
    echo "Would have expired this resource, unset $DELETE_FLAG to enable"
  else
    echo "Expiring this instance NOW"
    INSTANCE_ID=$(curl -fq http://169.254.169.254/latest/meta-data/instance-id)

    if aws --region "$(nubis-region)" autoscaling terminate-instance-in-auto-scaling-group --instance-id "$INSTANCE_ID"; then
      echo "Issued AWS ASG Termination for $INSTANCE_ID"
    elif aws --region "$(nubis-region)" ec2 terminate-instances --instance-ids "$INSTANCE_ID"; then
      echo "Issued AWS Termination for $INSTANCE_ID"
    else
      echo "Issuing system shutdown now"
      shutdown -h now
    fi
  fi
fi
