#!/bin/bash

if [ "$(nubis-metadata status)" != 'ready' ]; then
    # Assume this is a build and exit silently
    exit 0
fi

# Load up proxy settings
if [ -r /etc/profile.d/proxy.sh ]; then
  # shellcheck disable=SC1091
  . /etc/profile.d/proxy.sh
fi

# Expose our project to fluentd
if nubis-metadata NUBIS_PROJECT > /dev/null 2>&1; then
    NUBIS_PROJECT=$(nubis-metadata NUBIS_PROJECT)
    export NUBIS_PROJECT
fi

# Expose our purpose to fluentd
if nubis-metadata NUBIS_PURPOSE > /dev/null 2>&1; then
    NUBIS_PURPOSE=$(nubis-metadata NUBIS_PURPOSE)
    export NUBIS_PURPOSE
fi

#Expose our stack to fluentd
if nubis-metadata NUBIS_STACK > /dev/null 2>&1; then
    NUBIS_STACK=$(nubis-metadata NUBIS_STACK)
    export NUBIS_STACK
fi

#Expose our environment to fluentd
if nubis-metadata NUBIS_ENVIRONMENT > /dev/null 2>&1; then
    NUBIS_ENVIRONMENT=$(nubis-metadata NUBIS_ENVIRONMENT)
    export NUBIS_ENVIRONMENT
fi

#Expose our arena to fluentd
if nubis-metadata NUBIS_ARENA > /dev/null 2>&1; then
    NUBIS_ARENA=$(nubis-metadata NUBIS_ARENA)
    export NUBIS_ARENA
fi

exec /opt/td-agent/embedded/bin/fluentd --log /var/log/td-agent/td-agent.log --daemon /var/run/td-agent/td-agent.pid
