[template]
src = "node_exporter.tmpl"
dest = "/var/run/node_exporter"
prefix = "/environments/%%ENVIRONMENT%%/global/node_exporter"

uid = 0
gid = 0
mode = "0750"

keys = [
    "/config"
]

reload_cmd = "/var/run/node_exporter"
