[template]
src = "node_exporter.tmpl"
dest = "/usr/local/sbin/nubis_node_exporter"
prefix = "/arenas/%%ARENA%%/global/node_exporter"

uid = 0
gid = 0
mode = "0750"

keys = [
    "/config"
]

reload_cmd = "/usr/local/sbin/nubis_node_exporter"
