#!/bin/bash

debian_puppet_version="3.7.3-1puppetlabs1"
redhat_puppet_version="3.7.3-1"

set -e

if [[ -f /etc/debian_version ]]; then
   # Install puppetlabs repository, we'll want access to more up to date puppet agents than what's
   # provided in Amazon's repositories.
   wget -O /tmp/puppetlabs-release-precise.deb https://apt.puppetlabs.com/puppetlabs-release-precise.deb
   sudo dpkg -i /tmp/puppetlabs-release-precise.deb
   rm -f /tmp/puppetlabs-release-precise.deb

   # Update repository caches
   sudo apt-get update

   # Install puppet
   sudo apt-get -y install puppet=${debian_puppet_version}   
elif [[ -f /etc/redhat_release ]]; then
   # Install puppetlabs repository, we'll want access to more up to date puppet agents than what's
   # provided in Amazon's repositories.
   sudo rpm -ivh http://yum.puppetlabs.com/puppetlabs-release-el-6.noarch.rpm

   # Update repository caches
   sudo yum -y update

   # Install puppet
   sudo yum -y install puppet-${redhat_puppet_version}
fi
