#!/bin/bash

declare api_key

# Load the settings from Consul
# shellcheck disable=SC1091
source /etc/nubis-config/datadog.sh

# Is DataDog disabled ?
if [[ "$api_key" == *"DISABLED"* ]]; then
  /etc/init.d/datadog-agent stop

  # Disable Consul service check
  if [ -r "/etc/consul/svc-datadog.json" ]; then
    gzip /etc/consul/svc-datadog.json
    /etc/init.d/consul reload
  fi
else

# Enable Consul service check
if [ -r "/etc/consul/svc-datadog.json.gz" ]; then
  gunzip /etc/consul/svc-datadog.json.gz
  /etc/init.d/consul reload
fi

# fix the config file (poor-man's Augeas)
perl -pi -e"s/^api_key: (.*)/api_key: $api_key/g" /etc/dd-agent/datadog.conf

# Restart datadog is all is well
/etc/init.d/datadog-agent configtest && /etc/init.d/datadog-agent restart

fi
