#!/bin/bash

set -e

# /usr/local/bin isn't set yet in our PATH
export PATH=/usr/local/bin:$PATH

eval "$(nubis-metadata)"

if [ -z "${NUBIS_SUDO_GROUPS}" ]; then
    NUBIS_SUDO_GROUPS_TMP="[]"
else
    NUBIS_SUDO_GROUPS_TMP=$(echo "${NUBIS_SUDO_GROUPS}" | sed -e's/^/["/g' | sed -e's/$/"]/' | sed -e's/,/","/g' )
fi

if [ -z "${NUBIS_USER_GROUPS}" ]; then
    NUBIS_USER_GROUPS_TMP="[]"
else
    NUBIS_USER_GROUPS_TMP=$(echo "${NUBIS_USER_GROUPS}" | sed -e's/^/["/g' | sed -e's/$/"]/' | sed -e's/,/","/g')
fi

cat <<EOF > /etc/nubis/puppet/nubis_users.pp
# Generated by gen-puppet.sh
class { 'nubis_users::setup':
    sudo_users    => ${NUBIS_SUDO_GROUPS_TMP},
    nubis_users   => ${NUBIS_USER_GROUPS_TMP},
}
EOF

nohup puppet apply --modulepath=/etc/puppet/modules /etc/nubis/puppet/nubis_users.pp >/dev/null 2>&1 &
