#!/usr/bin/env perl
use strict;

use Sys::Hostname;
use Socket;
use NetAddr::IP;

my $address = inet_ntoa( scalar gethostbyname( hostname() ) );

my $mask = shift || "24";

my $ip = NetAddr::IP->new("$address/$mask");

my @ips;
for my $addr ( @{ $ip->hostenumref } ) {
    push @ips, $addr->addr;
}

print join ",", @ips;
