#!/bin/bash -l

# Run a cronjob, and record start/end/status to prometheus metrics
# usage:
#  nubis-cron name-of-cron-job "commands to execute"

cleanup () {
 rm -f "$METRICS" 2>/dev/null
}
trap cleanup EXIT

METRICS_PATH=/var/lib/node_exporter/metrics

METRICS=$(mktemp)

JOB=$1
shift

START=$(date +%s)

bash -c "$*"

RV=$?

END=$(date +%s)
DURATION=$(( END - START ))

cat <<EOF > "$METRICS"
# HELP nubis_cron_end Metric created by nubis-cron
nubis_cron_end{cronjob="$JOB"} $END
# HELP nubis_cron_start Metric created by nubis-cron
nubis_cron_start{cronjob="$JOB"} $START
# HELP nubis_cron_duration Metric created by nubis-cron
nubis_cron_duration{cronjob="$JOB"} $DURATION
# HELP nubis_cron_status Metric created by nubis-cron
nubis_cron_status{cronjob="$JOB"} $RV
EOF

mv -f "$METRICS" "$METRICS_PATH/nubis_cron_$JOB.prom"

# Propagate exit code
exit $RV
