#!/bin/bash

# Simple log function
function log() {

    local LOGGER_BIN='/usr/bin/logger'
    local LOGMSG=$1

    # shellcheck disable=SC2128
    [ -z "$LOGMSG" ] && { echo "Usage: $FUNCNAME [log message]"; exit 1; }

    # Set up the logger command if the binary is installed
    if [ ! -x $LOGGER_BIN ]; then
        # If logger is not installed just stderr it out
        echo "$LOGMSG"
    else
        $LOGGER_BIN --stderr --priority local7.info --tag 'nubis-secret' "$LOGMSG"
    fi
}

# /usr/local/bin isn't set yet in our PATH
export PATH=/usr/local/bin:$PATH

USER_DATA=$(curl -fqs http://169.254.169.254/latest/user-data)
eval "$USER_DATA"

REGION=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq '.region' -r)

UNICREDS="/usr/local/bin/unicreds"

if [[ -z "${UNICREDS}" ]]; then log "unicreds not installed"; exit 1; fi
if [[ -z "${NUBIS_ENVIRONMENT}" ]]; then log "NUBIS_ENVIRONMENT variable does not exist"; exit 1; fi
if [[ -z "${NUBIS_PROJECT}" ]]; then log "NUBIS_PROJECT variable does not exist"; exit 1; fi
if [[ -z "${REGION}" ]]; then log "REGION variable does not exist"; exit 1; fi

if [ "$1" == "--global" ]; then
  shift;
  NUBIS_PROJECT=nubis
  PREFIX=nubis/$NUBIS_ENVIRONMENT
else
  PREFIX=$NUBIS_PROJECT/$NUBIS_ENVIRONMENT
fi

ACTION=$1
shift

SECRET=$1
shift

if [ "$ACTION" != "get" ] || [ ! "$SECRET" ]; then
    echo "Usage: $0 get secret"
    exit
fi

$UNICREDS --region "$REGION" "$ACTION" "$PREFIX/$SECRET" -E "environment:$NUBIS_ENVIRONMENT" -E "region:$REGION" -E "service:$NUBIS_PROJECT"
