#!/bin/bash
eval "$(curl -fqs http://169.254.169.254/latest/user-data)"

# Usage:
#  $> nubis-purpose
#  prints out your purpose
#
#  $> nubis-purpose "Web Server"
#  exits with true/false if the purpose you specify is ours
#
#  $> nubis-purpose "Web Server" some command
#  execs the specified command if the purpose specified is ours

if [ -z "$1" ]; then
  echo "$NUBIS_PURPOSE"
else
  purpose=$1
  shift
  if [ "$purpose" == "$NUBIS_PURPOSE" ]; then
    if [ -z "$@" ]; then
      exit 0
    else
      exec "$@"
    fi
  else
    exit 1
  fi
fi

