[template]
src = "nubis-users.tmpl"
dest = "/etc/puppet/yaml/nubis_users/common.yaml"
prefix = "/nubis-users"

keys = [
    "/global-admins",
    "/sudo-users",
    "/users",
]

reload_cmd = "puppet apply --hiera_config /etc/puppet/hiera.yaml --modulepath /etc/puppet/modules/ -e 'include nubis_users'"
