#!/bin/bash

set -x

# Be explicitly all-inclusive in our PATH, just to be safe
PATH="$HOME/bin:$(ruby -e 'puts Gem.user_dir')/bin:$PATH:/usr/local/sbin:/usr/sbin:/sbin"
export PATH

cd /tmp/tests || exit 1

gem install bundler --no-ri --no-rdoc --user-install -v 1.16.3
gem install io-console --no-ri --no-rdoc --user-install

# Install serverspec and what it needs
bundle install
bundle env
bundle show

# Run spec tests
bundle exec rake spec

STATUS=$?

# Cleanup after ourselves
rm -rf /tmp/tests

# Bubble up serverspec's results
exit $STATUS
