source 'https://rubygems.org'

if ENV.key?('PUPPET_VERSION')
  puppetversion = "= #{ENV['PUPPET_VERSION']}"
else
  puppetversion = ['< 4.0']
end

gem 'rake'
gem 'puppet-lint'
gem 'jsonlint'
gem 'librarian-puppet'
gem 'puppet', puppetversion
